version: "3"

services:
  web:
    build: .
    restart: always
    links:
      - db
      - redis
      - es
    ports:
      - "3000:3000"
    networks:
      - internal_network
      - external_network
    volumes:
      - ./files:/misskey/files
      - ./.config:/misskey/.config:ro

  redis:
    restart: always
    image: redis:4.0-alpine
    networks:
      - internal_network
    volumes:
      - ./redis:/data

  db:
    restart: always
    image: postgres:12.2-alpine
    networks:
      - internal_network
    env_file:
      - .config/docker.env
    volumes:
      - ./db:/var/lib/postgresql/data
    ports:
      - "15432:5432"

  es:
    restart: always
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.1
    environment:
      - "cluster.name=misskey_cluster"
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
      - "discovery.type=single-node"
      - "ingest.geoip.downloader.enabled=false"
    networks:
      - internal_network
    volumes:
      - ./elasticsearch:/usr/share/elasticsearch/data
    ports:
      - "19200:9200"

networks:
  internal_network:
    internal: true
  external_network:
